default:
  outputs:
    dev:
      dataset: steam_test
      fixed_retries: 1
      keyfile: <service account json>
      location: europe-west2
      method: service-account
      priority: interactive
      project: <project id>
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
