version: 2

models:
  - name: steam_user_tag_table
    description: ""
    columns:
      - name: appid
        data_type: int64
        description: ""
        tests:
            - not_null:
                severity: warn
      - name: tag
        data_type: string
        description: ""
        tests:
            - not_null:
                severity: warn
      - name: user_count
        data_type: int64
        description: ""
        tests:
            - not_null:
                severity: warn
  - name: rankings
    description: ""
    columns:
      - name: appid
        data_type: int64
        description: ""
        tests:
            - not_null:
                severity: warn
      - name: name
        data_type: string
        description: ""

      - name: price
        data_type: float64
        description: ""

      - name: developer
        data_type: string
        description: ""

      - name: rank
        data_type: int64
        description: ""

      - name: peak_in_game
        data_type: int64
        description: ""

      - name: date_added
        data_type: timestamp
        description: ""
    